### ISSUE TITLE
Error when dragging a file outside of the browser window in Firefox

### ISSUE THREAD

**Issue by mpharoah-d2l** [BrightspaceUILabs/file-uploader#53]
In Firefox, when a file is dragged outside of the browser window, the dragleave event targets an element outside of the page, and the javascript does not have permission to access any property on the event. To work around this, a try-catch block must be used to catch the permission denied errors that occur when dragging a file outside of the browser, and then handle this case appropriately.

**Comment by dlockhart** [comment]
@mpharoah-d2l is there an easy fix you can see that you could make to this component?

**Comment by mpharoah-d2l** [comment]
I looked into it further, and it looks like the error actually gets thrown from the shadydom code, not from this web component, so it may be impossible to fix. Unfortunately, it completely breaks the page until you either refresh or drag another file back into the window and then drop it. I was able to work around this when we were using a React component, but I don't know if it will be possible to fix in a web component.

**Comment by mpharoah-d2l** [comment]
Actually, it looks like this component doesn't break the whole page if you drag outside of the window and drop, since the error is mostly contained in the component, so this isn't quite as severe as I thought.

**Comment by dbatiste** [comment]
Perhaps checking the `relatedTarget` of the drag and/or drop events can help?

**Comment by mpharoah-d2l** [comment]
The entire event is protected. You can't even call `Object.keys()` on it without it throwing an exception. I'm assuming it's a bug in Firefox

**Comment by dlockhart** [comment]
Is there a particular line of code in here where we could wrap a `try`-`catch` around it to swallow the error? Or is it only detectable outside of the component in a consumer?

**Comment by mpharoah-d2l** [comment]
I don't think so. If the code received the native event directly from the browser, then you could simply wrap `event.preventDefault();` on line 272 in a try-catch; however, the error gets thrown from [a file in the ShadyDOM](https://github.com/webcomponents/shadydom/blob/master/src/patch-events.js) shim before it even gets to this code.

**Comment by dlockhart** [comment]
Oh dear. OK so maybe we can close this issue and just deal with `webcomponentsjs` or Firefox directly?

**Comment by dlockhart** [comment]
Closing this since Firefox now natively supports shadow DOM so won't be using the polyfill.
